# Generated by Django 4.1 on 2023-04-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(blank=True, choices=[('PR', 'Pinar del Rio'), ('ART', 'Artemisa'), ('HAB', 'La Habana'), ('MAY', 'Mayabeque'), ('MAT', 'Matanzas'), ('VCL', 'Villa Clara'), ('CFG', 'Cienfuegos'), ('SS', 'Santi Spiritu'), ('CAV', 'Ciego de Avila'), ('TUN', 'Las Tunas'), ('HOL', 'Holguin'), ('GRM', 'Granma'), ('STG', 'Santiago de Cuba'), ('GTM', 'Guantanamo'), ('IJV', 'Isla de la Juventud')], max_length=50, null=True, verbose_name='Provincia que atiende'),
        ),
    ]
